import Foundation

struct CurrencyData {
    static let allCurrencies: [Currency] = [
        Currency(code: "AED", name: "UAE Dirham", flag: "🇦🇪"),
        Currency(code: "AFN", name: "Afghan Afghani", flag: "🇦🇫"),
        Currency(code: "ALL", name: "Albanian Lek", flag: "🇦🇱"),
        Currency(code: "AMD", name: "Armenian Dram", flag: "🇦🇲"),
        Currency(code: "ANG", name: "Netherlands Antillean Guilder", flag: "🇳🇱"),
        Currency(code: "AOA", name: "Angolan Kwanza", flag: "🇦🇴"),
        Currency(code: "ARS", name: "Argentine Peso", flag: "🇦🇷"),
        Currency(code: "AUD", name: "Australian Dollar", flag: "🇦🇺"),
        Currency(code: "AWG", name: "Aruban Florin", flag: "🇦🇼"),
        Currency(code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿"),
        Currency(code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", flag: "🇧🇦"),
        Currency(code: "BBD", name: "Barbadian Dollar", flag: "🇧🇧"),
        Currency(code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩"),
        Currency(code: "BGN", name: "Bulgarian Lev", flag: "🇧🇬"),
        Currency(code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭"),
        Currency(code: "BIF", name: "Burundian Franc", flag: "🇧🇮"),
        Currency(code: "BMD", name: "Bermudan Dollar", flag: "🇧🇲"),
        Currency(code: "BND", name: "Brunei Dollar", flag: "🇧🇳"),
        Currency(code: "BOB", name: "Bolivian Boliviano", flag: "🇧🇴"),
        Currency(code: "BRL", name: "Brazilian Real", flag: "🇧🇷"),
        Currency(code: "BSD", name: "Bahamian Dollar", flag: "🇧🇸"),
        Currency(code: "BTC", name: "Bitcoin", flag: "₿"),
        Currency(code: "BTN", name: "Bhutanese Ngultrum", flag: "🇧🇹"),
        Currency(code: "BWP", name: "Botswanan Pula", flag: "🇧🇼"),
        Currency(code: "BYN", name: "Belarusian Ruble", flag: "🇧🇾"),
        Currency(code: "BZD", name: "Belize Dollar", flag: "🇧🇿"),
        Currency(code: "CAD", name: "Canadian Dollar", flag: "🇨🇦"),
        Currency(code: "CDF", name: "Congolese Franc", flag: "🇨🇩"),
        Currency(code: "CHF", name: "Swiss Franc", flag: "🇨🇭"),
        Currency(code: "CLF", name: "Chilean Unit of Account (UF)", flag: "🇨🇱"),
        Currency(code: "CLP", name: "Chilean Peso", flag: "🇨🇱"),
        Currency(code: "CNH", name: "Chinese Yuan (Offshore)", flag: "🇨🇳"),
        Currency(code: "CNY", name: "Chinese Yuan", flag: "🇨🇳"),
        Currency(code: "COP", name: "Colombian Peso", flag: "🇨🇴"),
        Currency(code: "CRC", name: "Costa Rican Colón", flag: "🇨🇷"),
        Currency(code: "CUC", name: "Cuban Convertible Peso", flag: "🇨🇺"),
        Currency(code: "CUP", name: "Cuban Peso", flag: "🇨🇺"),
        Currency(code: "CVE", name: "Cape Verdean Escudo", flag: "🇨🇻"),
        Currency(code: "CZK", name: "Czech Republic Koruna", flag: "🇨🇿"),
        Currency(code: "DJF", name: "Djiboutian Franc", flag: "🇩🇯"),
        Currency(code: "DKK", name: "Danish Krone", flag: "🇩🇰"),
        Currency(code: "DOP", name: "Dominican Peso", flag: "🇩🇴"),
        Currency(code: "DZD", name: "Algerian Dinar", flag: "🇩🇿"),
        Currency(code: "EGP", name: "Egyptian Pound", flag: "🇪🇬"),
        Currency(code: "ERN", name: "Eritrean Nakfa", flag: "🇪🇷"),
        Currency(code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹"),
        Currency(code: "EUR", name: "Euro", flag: "🇪🇺"),
        Currency(code: "FJD", name: "Fijian Dollar", flag: "🇫🇯"),
        Currency(code: "FKP", name: "Falkland Islands Pound", flag: "🇫🇰"),
        Currency(code: "GBP", name: "British Pound Sterling", flag: "🇬🇧"),
        Currency(code: "GEL", name: "Georgian Lari", flag: "🇬🇪"),
        Currency(code: "GGP", name: "Guernsey Pound", flag: "🇬🇬"),
        Currency(code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭"),
        Currency(code: "GIP", name: "Gibraltar Pound", flag: "🇬🇮"),
        Currency(code: "GMD", name: "Gambian Dalasi", flag: "🇬🇲"),
        Currency(code: "GNF", name: "Guinean Franc", flag: "🇬🇳"),
        Currency(code: "GTQ", name: "Guatemalan Quetzal", flag: "🇬🇹"),
        Currency(code: "GYD", name: "Guyanaese Dollar", flag: "🇬🇾"),
        Currency(code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰"),
        Currency(code: "HNL", name: "Honduran Lempira", flag: "🇭🇳"),
        Currency(code: "HRK", name: "Croatian Kuna", flag: "🇭🇷"),
        Currency(code: "HTG", name: "Haitian Gourde", flag: "🇭🇹"),
        Currency(code: "HUF", name: "Hungarian Forint", flag: "🇭🇺"),
        Currency(code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩"),
        Currency(code: "ILS", name: "Israeli New Sheqel", flag: "🇮🇱"),
        Currency(code: "IMP", name: "Manx pound", flag: "🇮🇲"),
        Currency(code: "INR", name: "Indian Rupee", flag: "🇮🇳"),
        Currency(code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶"),
        Currency(code: "IRR", name: "Iranian Rial", flag: "🇮🇷"),
        Currency(code: "ISK", name: "Icelandic Króna", flag: "🇮🇸"),
        Currency(code: "JEP", name: "Jersey Pound", flag: "🇯🇪"),
        Currency(code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲"),
        Currency(code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴"),
        Currency(code: "JPY", name: "Japanese Yen", flag: "🇯🇵"),
        Currency(code: "KES", name: "Kenyan Shilling", flag: "🇰🇪"),
        Currency(code: "KGS", name: "Kyrgystani Som", flag: "🇰🇬"),
        Currency(code: "KHR", name: "Cambodian Riel", flag: "🇰🇭"),
        Currency(code: "KMF", name: "Comorian Franc", flag: "🇰🇲"),
        Currency(code: "KPW", name: "North Korean Won", flag: "🇰🇵"),
        Currency(code: "KRW", name: "South Korean Won", flag: "🇰🇷"),
        Currency(code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼"),
        Currency(code: "KYD", name: "Cayman Islands Dollar", flag: "🇰🇾"),
        Currency(code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿"),
        Currency(code: "LAK", name: "Laotian Kip", flag: "🇱🇦"),
        Currency(code: "LBP", name: "Lebanese Pound", flag: "🇱🇧"),
        Currency(code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰"),
        Currency(code: "LRD", name: "Liberian Dollar", flag: "🇱🇷"),
        Currency(code: "LSL", name: "Lesotho Loti", flag: "🇱🇸"),
        Currency(code: "LYD", name: "Libyan Dinar", flag: "🇱🇾"),
        Currency(code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦"),
        Currency(code: "MDL", name: "Moldovan Leu", flag: "🇲🇩"),
        Currency(code: "MGA", name: "Malagasy Ariary", flag: "🇲🇬"),
        Currency(code: "MKD", name: "Macedonian Denar", flag: "🇲🇰"),
        Currency(code: "MMK", name: "Myanma Kyat", flag: "🇲🇲"),
        Currency(code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳"),
        Currency(code: "MOP", name: "Macanese Pataca", flag: "🇲🇴"),
        Currency(code: "MRO", name: "Mauritanian Ouguiya (pre-2018)", flag: "🇲🇷"),
        Currency(code: "MRU", name: "Mauritanian Ouguiya", flag: "🇲🇷"),
        Currency(code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺"),
        Currency(code: "MVR", name: "Maldivian Rufiyaa", flag: "🇲🇻"),
        Currency(code: "MWK", name: "Malawian Kwacha", flag: "🇲🇼"),
        Currency(code: "MXN", name: "Mexican Peso", flag: "🇲🇽"),
        Currency(code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾"),
        Currency(code: "MZN", name: "Mozambican Metical", flag: "🇲🇿"),
        Currency(code: "NAD", name: "Namibian Dollar", flag: "🇳🇦"),
        Currency(code: "NGN", name: "Nigerian Naira", flag: "🇳🇬"),
        Currency(code: "NIO", name: "Nicaraguan Córdoba", flag: "🇳🇮"),
        Currency(code: "NOK", name: "Norwegian Krone", flag: "🇳🇴"),
        Currency(code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵"),
        Currency(code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿"),
        Currency(code: "OMR", name: "Omani Rial", flag: "🇴🇲"),
        Currency(code: "PAB", name: "Panamanian Balboa", flag: "🇵🇦"),
        Currency(code: "PEN", name: "Peruvian Nuevo Sol", flag: "🇵🇪"),
        Currency(code: "PGK", name: "Papua New Guinean Kina", flag: "🇵🇬"),
        Currency(code: "PHP", name: "Philippine Peso", flag: "🇵🇭"),
        Currency(code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰"),
        Currency(code: "PLN", name: "Polish Zloty", flag: "🇵🇱"),
        Currency(code: "PYG", name: "Paraguayan Guarani", flag: "🇵🇾"),
        Currency(code: "QAR", name: "Qatari Rial", flag: "🇶🇦"),
        Currency(code: "RON", name: "Romanian Leu", flag: "🇷🇴"),
        Currency(code: "RSD", name: "Serbian Dinar", flag: "🇷🇸"),
        Currency(code: "RUB", name: "Russian Ruble", flag: "🇷🇺"),
        Currency(code: "RWF", name: "Rwandan Franc", flag: "🇷🇼"),
        Currency(code: "SAR", name: "Saudi Riyal", flag: "🇸🇦"),
        Currency(code: "SBD", name: "Solomon Islands Dollar", flag: "🇸🇧"),
        Currency(code: "SCR", name: "Seychellois Rupee", flag: "🇸🇨"),
        Currency(code: "SDG", name: "Sudanese Pound", flag: "🇸🇩"),
        Currency(code: "SEK", name: "Swedish Krona", flag: "🇸🇪"),
        Currency(code: "SGD", name: "Singapore Dollar", flag: "🇸🇬"),
        Currency(code: "SHP", name: "Saint Helena Pound", flag: "🇸🇭"),
        Currency(code: "SLE", name: "Sierra Leonean Leone", flag: "🇸🇱"),
        Currency(code: "SLL", name: "Sierra Leonean Leone (pre-2022)", flag: "🇸🇱"),
        Currency(code: "SOS", name: "Somali Shilling", flag: "🇸🇴"),
        Currency(code: "SRD", name: "Surinamese Dollar", flag: "🇸🇷"),
        Currency(code: "STD", name: "São Tomé and Príncipe Dobra (pre-2018)", flag: "🇸🇹"),
        Currency(code: "STN", name: "São Tomé and Príncipe Dobra", flag: "🇸🇹"),
        Currency(code: "SVC", name: "Salvadoran Colón", flag: "🇸🇻"),
        Currency(code: "SYP", name: "Syrian Pound", flag: "🇸🇾"),
        Currency(code: "SZL", name: "Swazi Lilangeni", flag: "🇸🇿"),
        Currency(code: "THB", name: "Thai Baht", flag: "🇹🇭"),
        Currency(code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯"),
        Currency(code: "TMT", name: "Turkmenistani Manat", flag: "🇹🇲"),
        Currency(code: "TND", name: "Tunisian Dinar", flag: "🇹🇳"),
        Currency(code: "TOP", name: "Tongan Paʻanga", flag: "🇹🇴"),
        Currency(code: "TRY", name: "Turkish Lira", flag: "🇹🇷"),
        Currency(code: "TTD", name: "Trinidad and Tobago Dollar", flag: "🇹🇹"),
        Currency(code: "TWD", name: "New Taiwan Dollar", flag: "🇹🇼"),
        Currency(code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿"),
        Currency(code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦"),
        Currency(code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬"),
        Currency(code: "USD", name: "United States Dollar", flag: "🇺🇸"),
        Currency(code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾"),
        Currency(code: "UYW", name: "Unidad Previsional", flag: "🇺🇾"),
        Currency(code: "UZS", name: "Uzbekistan Som", flag: "🇺🇿"),
        Currency(code: "VED", name: "Venezuelan Bolívar Soberano", flag: "🇻🇪"),
        Currency(code: "VES", name: "Venezuelan Bolívar Soberano", flag: "🇻🇪"),
        Currency(code: "VND", name: "Vietnamese Dong", flag: "🇻🇳"),
        Currency(code: "VUV", name: "Vanuatu Vatu", flag: "🇻🇺"),
        Currency(code: "WST", name: "Samoan Tala", flag: "🇼🇸"),
        Currency(code: "XAF", name: "CFA Franc BEAC", flag: "🇨🇲"),
        Currency(code: "XCD", name: "East Caribbean Dollar", flag: "🇦🇬"),
        Currency(code: "XDR", name: "Special Drawing Rights", flag: "🏦"),
        Currency(code: "XOF", name: "CFA Franc BCEAO", flag: "🇸🇳"),
        Currency(code: "XPF", name: "CFP Franc", flag: "🇵🇫"),
        Currency(code: "YER", name: "Yemeni Rial", flag: "🇾🇪"),
        Currency(code: "ZAR", name: "South African Rand", flag: "🇿🇦"),
        Currency(code: "ZMW", name: "Zambian Kwacha", flag: "🇿🇲"),
        Currency(code: "ZWL", name: "Zimbabwean Dollar", flag: "🇿🇼")
    ]
    
    static func currency(for code: String) -> Currency? {
        return allCurrencies.first { $0.code == code }
    }
    
    static func popularCurrencies() -> [Currency] {
        let popularCodes = ["USD", "EUR", "GBP", "JPY", "AUD", "CAD", "CHF", "CNY", "SEK", "NZD", "PLN"]
        return popularCodes.compactMap { currency(for: $0) }
    }
    
    static func searchCurrencies(query: String) -> [Currency] {
        let lowercaseQuery = query.lowercased()
        return allCurrencies.filter { currency in
            currency.code.lowercased().contains(lowercaseQuery) ||
            currency.name.lowercased().contains(lowercaseQuery)
        }
    }
}